spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytask?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  mvc:
    view:
      suffix: /
      prefix: .jsp
mybatis:
  mapper-locations: classpath:com/bosssoft/mytask/mapper/*.xml  #配置mapper文件路径
  type-aliases-package: com.bosssoft.mytask.entity
